name: test & maybe release
on:
  push:
    branches:
      - master # with #262 - ${{{ github.default_branch }}}
  pull_request:
    branches:
      - master # with #262 - ${{{ github.default_branch }}}

jobs:

  test-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [16]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run --if-present test:node
      - uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # v3.1.0
        with:
          flags: node
